### ISSUE TITLE
Tuple and Arrow.

### ISSUE THREAD

**Issue by diasbruno** [origamitower/folktale#126]
Hi,

I've been working on an implementation of `tuple` for folktale, specially to try to get an `Arrow` spec for javascript.

I'm adding this issue to show the first work of it and provide updates (I'm still working on tuple, later I'll try get Arrows).

[@diasbruno/folktale#feature/tuple](https://github.com/origamitower/folktale/compare/master...diasbruno:feature/tuple)

**Comment by robotlolita** [comment]
Ah, since those aren't on the roadmap, can you submit a proposal for those features first?

**Comment by diasbruno** [comment]
Sure. When I finish I'll submit a proposal.

**Comment by diasbruno** [comment]
@robotlolita I'll close this issue and open a proposal for `tuples` first. Thank you.
