### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jgranduel** [origamitower/folktale#149]
Hi, 

just decovering Folktale-2.0.0. Great!
I came across a small mistake on documentation, maybe not yet updated:
I started from page http://folktale.origamitower.com/docs/v2.0.0/download/
where appears this code: 

```javascript
    const Maybe = require('folktale/data/maybe'); // wrong path
    const compose = require('folktale/core/lambda/compose');
```
require path is indeed correct on page:
http://folktale.origamitower.com/docs/v2.0.0/migrating/from-data.maybe/
or on http://folktale.origamitower.com/docs/v2.0.0/overview/

```javascript
    const Maybe = require('folktale/maybe');
```
Good luck with this new version!

**Comment by robotlolita** [comment]
Ah, indeed, I missed that when updating the docs. Thanks for reporting :)
