### ISSUE TITLE
ESLint no-unused-vars trigger on Union types

### ISSUE THREAD

**Issue by JesterXL** [origamitower/folktale#150]
Minor note, using this ESLint rule http://eslint.org/docs/rules/no-unused-vars, it's not catching that the Union types are actually being used in .matchWith methods. It's really weird, not sure how to solve it. Some teams in my company are forcing this rule, so curious if we can maybe fix the ESLint, or perhaps I'm missing something obvious.

**Comment by robotlolita** [comment]
Mmh, can you give an example of the problem? I didn't really understand what's wrong here.

**Comment by JesterXL** [comment]
For Maybe:

```javascript
const {Just, Nothing} = require('maybe');
someFunction().matchWith({
   Just: _ => true,
   Nothing: _ => false
});
```

That rule for some reason thinks `Just` and `Nothing` aren't used, but they are.

**Comment by volkanunsal** [comment]
@JesterXL You don't need to import the type classes to use `matchWith`.

**Comment by JesterXL** [comment]
@volkanunsal Yeah, I tried that, but get null pointers at runtime. Sorry for the trouble, both of y'all, I didn't think it'd be this difficult to quickly duplicate; bear with me as I get this simple repo working locally, and I'll show you what I'm talking about.

**Comment by JesterXL** [comment]
I figured it out, I was importing just the variants, not the union itself.
