### ISSUE TITLE
calling willMatchWith on a future() has uncaught error of missing 'listen' of undefined

### ISSUE THREAD

**Issue by niksosf** [origamitower/folktale#158]
Hi there, 

https://codesandbox.io/s/21o6kqn4zr

I made a simple sandbox here to show the problem, please look at the console, it's the normale console in your browser. 

In a nutshell, if we did

```
import { task } from "folktale/concurrency/task";

const delay = ms =>
  task(res => {
    setTimeout(() => res.resolve(ms), ms);
  });

const taskA = delay(1000);

console.log('taskA')
taskA.run().future().willMatchWith({
  Resolved: console.log,
  Rejected: console.log,
  Canceled: console.log
})
```
will throw 
```
Uncaught TypeError: Cannot read property 'listen' of undefined
    at Object.onResolved (VM3955 dll.js:19248)
    at Object.Resolved (VM3955 dll.js:10379)
    at InternalConstructor.matchWith (VM3955 dll.js:419)
    at _loop (VM3955 dll.js:10376)
    at moveToState (VM3955 dll.js:10392)
    at Object.onResolved (VM3955 dll.js:10531)
    at Object.Resolved (VM3955 dll.js:10379)
    at InternalConstructor.matchWith (VM3955 dll.js:419)
    at _loop (VM3955 dll.js:10376)
    at moveToState (VM3955 dll.js:10392)
    at Deferred.resolve (VM3955 dll.js:10432)
    at Object.resolve (VM3955 dll.js:11016)
    at eval
```

**Comment by joseaquino** [comment]
You are calling a method that doesn't exist, I think this is what you are trying to do:
```javascript
import { task } from "folktale/concurrency/task";

const delay = ms =>
  task(res => {
    setTimeout(() => res.resolve(ms), ms);
  });

const taskA = delay(1000);

console.log('taskA')
// - taskA.run().future().willMatchWith({
taskA.run().future().listen({
  onResolved: console.log,
  onRejected: console.log,
  onCanceled: console.log
})
```

**Comment by niksosf** [comment]
hi @joseaquino thanks for the help! Your code indeed worked. 

I was under the impression formed with reading the migration guide (of which I attached a screenshot) that `willMatchWith` was the replacement for `fork`. 

Is `listen` the de facto method to call to execute the side effects? 

<img width="796" alt="screen shot 2017-10-11 at 4 59 07 pm" src="https://user-images.githubusercontent.com/79443/31448868-c080163e-aea5-11e7-860e-a2c89742591e.png">

**Comment by joseaquino** [comment]
Hey @niksosf, glad it worked.

And you are right, that part of the documentation seems to be outdated, I would suggest submitting a pull request to update that part of the documentation, if you go back to that part of the documentation, on the top right corner there will be a button that says "IMPROVE THIS PAGE" where you can fork and submit the change and help others in the future not get stuck with the same issue.

Cheers!

**Comment by niksosf** [comment]
Gotcha! Thanks again, really appreciate it!

**Comment by robotlolita** [comment]
Ah, oops, the documentation is wrong here :x (it's on the part that isn't automatically verified by the automated testing stuff too).

`Future.willMatchWith({ ... })` requires every function to return a new Future, so the proper way of using it would be:

```js
import { task } from "folktale/concurrency/task";
import * as future from "folktale/concurrency/future";

const delay = ms =>
  task(res => {
    setTimeout(() => res.resolve(ms), ms);
  });

const taskA = delay(1000);

console.log('taskA')
taskA.run().future().willMatchWith({
  Resolved: (value) => {
    console.log(value);
    return future.of(value);
  },
  Rejected: (reason) => {
    console.log(reason);
    return future.rejected(reason);
  },
  Canceled: () => {
    console.log('cancelled');
    return task(resolver => resolver.cancel()).run().future();
  }
});
```

You use it when you want to transform all possible states from a future (or Task, which has the same `.willMatchWith` method that expects you to return a new Task) at once. If you just want to perform side-effects, then `.listen` is the method for that.

As for the equivalent of `.fork`, that would be:

```js
// Folktale 1
task.fork(onError, onSuccess);

// Folktale 2
task.run().listen({
  Resolved: onSuccess,
  Rejected: onError,
  Cancelled: onCancel
});
```

I do agree that the error message here is pretty useless :<

**Comment by niksosf** [comment]
Hey @robotlolita , nice of the authors to put automated check on even the docs, it seems like. -- Oh believe me, even the time I spent on researching this will be minor compared with the time I'll save with the safer code I'll write with it ;) 

That makes *a lot* of sense, because the way `listen` is describe elsewhere on the same doc. The way I understand it is that `listen` is a straightforward unleashing the value to do some side-effect after a one off async action inside the task. Fair enough. 

And `willMatchWith` will be used for continuing chaining/mapping, like you already said, transforming the data. 

here's that snippet on `listen`
<img width="728" alt="screen shot 2017-10-11 at 5 19 24 pm" src="https://user-images.githubusercontent.com/79443/31450140-fb306736-aea8-11e7-8da2-25a256eeeabe.png">
