### ISSUE TITLE
nullableToResult should take a fallback value

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#162]
Currently `nullableToValidation` takes a fallback value, but `nullableToResult` doesn't. This is inconsistent and not very useful :) We can make this change in a backwards compatible way by checking the number of arguments provided so yay.

**Comment by niksosf** [comment]
Wouldn't it be nicer for nullableToResult to work with as point-free  if it's curried and perhaps have the fallback value in the first position? 

kind of like `ramda`'s `[propOr](http://ramdajs.com/docs/#propOr)` : `propOr('key', 'fallback value', ObjectInQuestion)` so that we can pass the point-free propOr applied with just the first arguments. 

```js
Result
  .Ok({hey: 'ho! lets go'})
  .map(propOr('key', 'fallback value'))
```

So with `nullableToResult` (and `nullableToValidate` that inspired it), we can do
```js
Resul.try( () => fetch('api.com')).chain(Result.fromNullable('fallbackvalue'))
```

What do you think?

**Comment by ashton** [comment]
Hello! I've got a question related to this issue.

Since `Result.Error` has a method called `getOrElse` (which from what I understood is the safe way of getting the value out of the monad), and you pass a default value in `getOrElse` call, what is the purpose of passing a default value to `Result.fromNullable` too since this will be ignored when we call `getOrElse` on `Result.Error`?

**Comment by niksosf** [comment]
@ashton One thing I can think of is that if your pipe line has multiple operations each of which has the risk 
 f producing a `null` value, then you can adjust the `Result.Error` for each operations to make it more traceable. getOrElse is most certainly at the end of the pipeline so, it is harder to pinpoint which of the steps gives the `null`

`Right(personels)
.map(getLeader)
.chain(fromNullable("No leader"))
.map(getAddress)
.chain(fromNullable("no address"))
.map(getAptNumber)
.chain(fromNullable('No apt'))
.getOrElse("something else went wrong")
`
A very bad example :), I know that's probably better done with `propOr` with ramda, but just for answering your question. Hope it helps

**Comment by robotlolita** [comment]
@niksosf Folktale 1 went the currying route, but it causes more trouble than it's worth in an untyped language like JavaScript, particularly when you mix in variadic application. See https://folktale.origamitower.com/docs/v2.3.0/misc/design-principles/#arrow-functions-over-currying. Partialise (https://folktale.origamitower.com/api/v2.3.0/en/folktale.core.lambda.partialize.partialize.html), which is the equivalent of Scala's holes and Scheme's cut operator, would be more widely used if the overhead of checking for roles at runtime wasn't so big.

So, most of the time, just using arrow functions is a better idea (performance-wise, and principle-of-least-astonishment-wise).

---

@ashton it's more of a semantics thing. Result is biased towards successes, so we make working with the successful value the straightforward path, and require you to do a bit more of work to handle failures. To the point that `.getOrElse(default)` ignores the existing failure and uses `default` as the result (since you must return a value of the same type as the Ok side).

You can still try to recover from failures, just not with `.getOrElse`. For example, you could use:

```js
const contents =
  read("my-file.txt")
  .orElse(error => {
    if (error instanceof ENotExists) {
      return Result.Ok("This is the start of your new file...");
    } else {
      return Result.Error(error);
    }
  })
  .unsafeGet();
```

In this case, you'd recover from a file read error if it just happens that the file you're trying to open doesn't exist, but you still want it to fail when there's a device or permission error. Though a better idea here would be to use `.matchWith` instead of a sequence of `.orElse` and `.unsafeGet`.

The "safe" part in the documentation just means that the function won't throw an exception. Sometimes you *do* want things to throw exceptions, though. And sometimes you don't care about whether the value is an Ok or an Error, and there you could use `.merge()`.

**Comment by ashton** [comment]
In the above case, you would get an exception if you weren't able to read the file, because `unsafeGet` only works for `Ok` type, right?

The only way of getting the actual `Result.Error` value is by pattern matching it with `matchWith`

**Comment by robotlolita** [comment]
@ashton You can manipulate the value with other functions (like orElse and mapError) too, but yeah, both unsafeGet and getOrElse ignore the value.

We could make unsafeGet more useful by incorporating the object in the error message somehow, but then every object would need to implement some form of translating to error information in that case, since just calling `.toString()` on it is likely to yield confusing results.

The fact that `unsafeGet` doesn't take an optional error message as well makes debugging things a lot less fun if you're using it, so there's room for improvement there.
