### ISSUE TITLE
Implement Data.Task

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#17]
Implement a new Data.Task library based on Siren's cancellable tasks (https://github.com/siren-lang/siren/blob/master/runtime/src/Concurrency.siren).

See https://github.com/folktale/data.task/issues/35#issuecomment-220382518 for details

**Comment by syaiful6** [comment]
@robotlolita does it mean the Task part is same as current implementation? If, so it just need Future and Task Execution, right?

**Comment by robotlolita** [comment]
@syaiful6 it's very similar, but the resource handling and cancellation brings in some differences.

The effort to explain turned out to be more than the effort to implement it, so I just started a new branch and implemented it (https://github.com/origamitower/folktale/blob/patch/data.task/src/data/task/core.js). I should finish the rest of the operations later this week.
