### ISSUE TITLE
Symbol is undefined error thrown inside ie11

### ISSUE THREAD

**Issue by MonkeyJumps** [origamitower/folktale#172]
I get the following error message inside my console log when my page is loaded.

**

> Symbol is undefined error thrown inside ie11.

**

![image](https://user-images.githubusercontent.com/812636/35168542-2c7c3cee-fd0e-11e7-94e1-21712303f25b.png)

When i navigate to the error link inside my bundle file. I am taken to the union.js file and the following code block

![image](https://user-images.githubusercontent.com/812636/35168603-61d31ffc-fd0e-11e7-95a7-149fa4afc45c.png)

### Steps to reproduce

install
npm install --save-dev folktale

include on page 

const Validation = require('folktale/validation') //from folktalejs
const Success = Validation.Success
const Failure = Validation.Failure

#### Expected behaviour

Application should run with out error when loading page. It runs fine in every other browser but ie11.

#### Observed behaviour

i have tried install the es5-shim and es6-shim there was no change to behavior.

### Environment

(Describe the environment where the problem happens. This usually includes:

  - OS windows 10
  - JavaScript VM
 - node v7.9
  - Folktale version 2.0.1
)

**Comment by nyrosmith** [comment]
Symbols aren't supported in IE11 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
But it can be polyfilled. I think you'll run into more issues with unsupported features on IE...

**Comment by robotlolita** [comment]
@MonkeyJumps folktale uses ES2015 features (like Symbol), so in older platforms you'll need shims.

I don't know what IE11 implements, but you may have to include both es6-shim (https://github.com/es-shims/es6-shim) and es5-shim (https://github.com/es-shims/es5-shim).

**Comment by MonkeyJumps** [comment]
@nyrosmith i just tried to install es6-symbol and I got the same error.
@robotlolita I also tried to install es5-shim and es6-shim before I created this issue.

I will clear cache uninstall and re-install and give it another go. Here is my package.json if you're interested. I don't have es5 or es6 installed this round of testing 

{
  "name": "fusion",
  "version": "3.0.0-rc.11",
  "description": "Fusion 3",
  "dependencies": {
    "boolean": "^0.1.2",
    "file-dialog": "0.0.6",
    "lodash": "^4.17.4",
    "promise-polyfill": "^6.0.2",
    "prop-types": "^15.6.0",
    "query-string": "^4.3.4",
    "react": "^15.5.4",
    "react-context-menus": "^1.0.9",
    "react-dom": "^15.5.4",
    "react-modal": "^1.7.7",
    "react-select": "^1.0.0-rc.5",
    "react-simple-dropdown": "^3.2.0",
    "whatwg-fetch": "^2.0.3"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-jest": "^22.0.6",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.22.0",
    "babel-runtime": "^6.23.0",
    "classnames": "^2.2.5",
    "css-loader": "^0.28.0",
    "es6-symbol": "^3.1.1",
    "folktale": "^2.0.1",
    "jest": "^22.1.3",
    "loader-utils": "^1.1.0",
    "moment": "^2.18.1",
    "node-sass": "^4.5.3",
    "ramda": "^0.25.0",
    "rc-checkbox": "^2.0.0",
    "react-datepicker": "^0.46.0",
    "regenerator-runtime": "^0.11.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.16.1",
    "url-parse": "^1.1.8",
    "webpack": "^2.4.1"
  },
  "scripts": {
    "build": "webpack",
    "test": "jest"
  }
}

**Comment by MonkeyJumps** [comment]
I just removed the es6-symbol package and install both es6-shim and es5-shim. There is no change. I still get the same error in ie11.

**Comment by MonkeyJumps** [comment]
ok installing the babel-polyfill got it working 
https://babeljs.io/docs/usage/polyfill/

**Comment by robotlolita** [comment]
Ah, sorry, I had only skimmed the report and missed the part where you mentioned you had already tried them.

It's supposed to work with es6-shim, though, so this is certainly a problem. I'll have to review the requisites for older platforms.

**Comment by MonkeyJumps** [comment]
@robotlolita I think it might be more an issue with how i set up babel and webpack. As described on the babel page, I had to not only install the babel-polyfill package but needed to update my webpack entry object.
https://babeljs.io/docs/usage/polyfill/
