### ISSUE TITLE
Documentation headlines partially not visible

### ISSUE THREAD

**Issue by andys8** [origamitower/folktale#187]
The headlines of the website are not fully visible if the window is not wide enough.

### Steps to reproduce

Having a browser window with width of 800 px.

#### Expected behaviour

Headlines readable

#### Observed behaviour

![image](https://user-images.githubusercontent.com/13085980/38219650-db7d5294-36d6-11e8-9ac9-2d3801c3dcb7.png)

### Environment

Desktop Chrome, Android Chrome, iOS Safari

### Additional information

Cause is this style with a negative margin (shortened).

```css
#content-panel .section-title {
    margin-left: -1em;
}
```

**Comment by robotlolita** [comment]
Duplicate of #102
