### ISSUE TITLE
Link in documentation not working

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [origamitower/folktale#198]
### Steps to reproduce

When reading the documentation explaining why Validators cannot have a `chain` method ( https://folktale.origamitower.com/docs/support/faq/#why-is-there-no-chain-for-validation ) the  following paragraph has a link that points to a 404:

> The **new documentation explains these similarities and differences** very concisely, and likens the Either/Result + .chain to JavaScript’s exceptions and the ; operator. Either/Result, Future, and Task all have Monad implementations that could be understood in terms of ;. That is, a regular code like var x = doX(); doY() would be equivalent to doX().chain((x) => doY()) if using the Monad implementation of those data structures.

The link that doesn't work is:

https://folktale.origamitower.com/api/en/folktale.src.data.result.html#how-does-result-compare-to-validation-

#### Expected behaviour

The link should exist and not point to 404.

**Comment by robotlolita** [comment]
Thanks, this should be fixed now :>
