### ISSUE TITLE
Show derivation doesn't display functions and symbols

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#25]
The Show derivation uses `JSON.stringify` to serialise values for which `typeof` returns something different from `object`, but these values include `function` and `symbol`, which are ignored by JSON serialisation:

```js
const { show, data } = require('folktale/core/adt');

const { Id } = data('Id', {
  Id(value){ return { value } }
}).derive(show);

Id(1); // => Id.Id({ value: 1 })
Id(x => x); // => Id.Id({ value: undefined })
Id(Symbol('foo')); // => Id.Id({ value: undefined })
```

This should probably use the common REPL representations of these two:

```js
Id(x => x) // => Id.Id({ value: [Function] })
Id(function foo(){ }) // => Id.Id({ value: [Function: foo] })
Id(Symbol('foo')) // => Id.Id({ value: Symbol(foo) })
```

**Comment by boris-marinov** [comment]
Hi, 

I fixed this, but I accidentally commited it to `master` , instead of creating a branch. https://github.com/origamitower/folktale/commit/c73ff0adfec2cf80e29aaba5d2a074b1f5d5e874

Delete or revert it, if you want.

Sorry.

**Comment by robotlolita** [comment]
Fixed in https://github.com/origamitower/folktale/commit/c73ff0adfec2cf80e29aaba5d2a074b1f5d5e874

**Comment by robotlolita** [comment]
Ah, I've been away and busy with other stuff, so sorry I took this long to reply :(

It's okay, accidents happen. I keep messing up with Git too :)

**Comment by boris-marinov** [comment]
Hi, 
I am glad that you are back - coding by myself is no fun :)
