### ISSUE TITLE
Asymmetry problem with `fantasy-land/ap`

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#49]
Currently fantasy-land methods are implemented by aliasing functions in the data structure. This does not work as well in the case of `fantasy-land/ap` since the arguments are flipped. For Validation and Either, this means that `a.ap(b)` and `b['fantasy-land/ap'](a)` *do not have the same behaviour*.

This happens because `Left` and `Failure` both return `this` in their Apply instance, but since `this` is different for each of them, their behaviours differ. In this case, `fantasy-land/ap` would have to be defined directly in the data structure, rather than relying on the aliasing helper.

**Comment by safareli** [comment]
could not it be implemented something like this
```js
['fantasy-land/ap'](fa) {
  return fa.ap(this) // this is old ap
}
```

**Comment by robotlolita** [comment]
You're right, and that's how it's implemented right now. The issue I was seeing was something else.

**Comment by joseaquino** [comment]
I have a question about this asymmetry situation, how do you implement multiple arguments to a wrapped function using the `['fantasy-land/ap]` version?

What I'm having trouble wrapping my head is, with using the `ap` method in Ramda, which first checks if there is a method named `'fantasy-land/ap'` which `'folktale/maybe'` has and runs with that, therefore I don't know how to turn this code:
```javascript
Maybe.of(x => y => x + y)
    .ap(Maybe.of(1))   // => Maybe.Just(y => 1 + y)
    .ap(Maybe.of(2))   // => Maybe.Just(3)

// This doesn't work
// ap is Ramdas implementation
compose(
    ap(Maybe.of(2)),
    ap(Maybe.of(1)),  // => ERROR: Maybe.Just#map expects a function, but was given 1
    Maybe.of
)(x => y => x + y)
```

**Comment by robotlolita** [comment]
@joseaquino ah, this is because the implementations of `ap` and `fantasy-land/ap` are different, Fantasy Land has changed the specification of this from v1 to v2.

With `ap` you have:

```js
Maybe.of(x => x).ap(Maybe.of(1));
// Translates to
Maybe.of(1).map(x => x)
```

With `fantasy-land/ap`, the order of the arguments is inverted, so:

```js
Maybe.of(1)['fantasy-land/ap'](Maybe.of(x => x));
// Translates to
Maybe.of(1).map(x => x)
```

This does make this kind of composition much harder. I'm not sure how'd be the best way of writing it in a point-free style using the new fantasy-land/ap tbh.

**Comment by joseaquino** [comment]
Yes, I saw that in v1 you apply values to a function, and you can keep applying values as long as a function is returned, but now in v2 is the other way around, you apply a unary function to a value.

I'll keep at it and if I find a solution I'll post it back here for future reference.

Thank you @robotlolita

**Comment by mattstyles** [comment]
There is a bit more info [here](https://github.com/fantasyland/fantasy-land/issues/242) about fantasy-land ap, which works `(value).ap(function)` rather than `(function).ap(value)`.

@davidchambers makes some great points about why it is implemented like this in that thread.

**Comment by joseaquino** [comment]
Hey @mattstyles, yes I found this later on and it seems that with the new FL specs you can only nest `ap` calls in order to apply multiple wrapped values to a curried function, therefore making it a little less elegant but it does stay correct on the idea of applying functions to values and not the incorrect way of applying values to function as @davidchambers states in the link you provided. The downside IMO is that it makes things more verbose. Thanks for the help!
