### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#5]
This is a major redesign of Folktale, and it's based on the following principles:
- Make a better use of the ECMAScript language, specially ES2015-and-future features.
  
  > Arrow functions, async/await, maps, and friends provide a good set of functionalities for basing a functional standard library on.
- Replace currying-by-default by a heavier use of arrow functions.
  
  > Currying is harder to reason about in dynamic languages because things can compose in too many ways, and there's no type system to enforce correct composition. Incorrect composition usually results in silent or late errors.
- Provide free-method versions of functions for This-Bind syntax
  
  > `list::groupBy(f)`, `list.sort(compare::on(first))` and others are clearer than their prefix counter-part, and we don't need to mutate things.
- Where possible, as long as it doesn't break our structure's laws, use the language's features/native methods.
  
  > Makes it easier to combine Folktale with other existing projects.
- All methods should provide complete documentation on why they exist, and how to use them (see https://github.com/siren-lang/siren/blob/master/documentation/notes/organisation-and-design.md#how-to-write-documentation). This is being done with https://github.com/origamitower/metamagical
- Monolithic package over several repositories.
  
  > It's easier to use, and maintain something in a monolithic package than it is to maintain it across several repositories. It also makes things more consistent.
- Logically grouped modules, containing only the absolutely minimum necessary for it.
  
  > Each module should be entirely self-contained, and contain only the minimum necessary for that particular functionality. Most of the time this means one function = one module, but not always (see the ADT module, and https://github.com/siren-lang/siren/blob/master/documentation/platform-design.md).

---

See https://github.com/origamitower/folktale/milestone/1 for tasks pending for this redesign.

**Comment by boris-marinov** [comment]
Hi,
I want to help.
What should I tackle first?

**Comment by robotlolita** [comment]
@boris-marinov I'll work on a more detailed roadmap this weekend.

**Comment by boris-marinov** [comment]
cool

**Comment by DrBoolean** [comment]
Meeee toooo

**Comment by robotlolita** [comment]
Hm, so things happened and I ended up not pushing it, but here's the roadmap: https://github.com/origamitower/folktale/blob/refactor/redesign/ROADMAP.org

Focus should probably be on Core.Iterables and porting the Data.Maybe/Either/Validation libraries for now.

**Comment by boris-marinov** [comment]
Great.
So, we need a repo and we need to decide on stuff like coding conventions (I'd pick standard.js), testing framework (I am a fan of nodeunit personally, but maybe something like jsverify would work better for our purposes) etc.

**Comment by robotlolita** [comment]
This will be the new (monolithic) repo.

I've added eslint rules, and configured a testing framework (mocha with jsverify for property-based testing). Most of the tests should be property-based tests, with example based tests as a fallback for things that are hard to model as properties.

Workflow-wise, we'll be using feature/topic branches, and merge them back into the main branch when the feature is done. A feature here can be a single function, if it's sufficiently independent.

The commit messages follow [Angular.js's commit conventions](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines).

(I should probably write a CONTRIBUTING.md document describing all of this. I'll try to work on this over the following week).

If there's anything missing, just let me know :)

**Comment by boris-marinov** [comment]
Everything looks super.
I see that you started with the Maybe type, I can use it as a blueprint for the Either type (gonna go through the previous version of Folktale too).

**Comment by sseppola** [comment]
Hi, I've been using Folktale for a little while, and I'm starting to become comfortable with how it works. I'd love to help out with v2!
I'm happy to do some documentation or have a go at one of data.conversions, data.validation, control.monad or control.async. What is the next thing you'd like done?

**Comment by boris-marinov** [comment]
Hi, 

This list was a bit old, as currently Validation and Conversions are done (and Control.Monad is in progress).

Check out the other issues of the repo for things that you can pick up. Almost all of them are related to the redesign!

**Comment by sseppola** [comment]
Ah, ok. So I can pick anything that's not "ready", "in progress" or assigned to someone?

**Comment by boris-marinov** [comment]
Yes.

**Comment by robotlolita** [comment]
Ah oops, I forgot we had a checklist for this issue. You can see the issues here https://waffle.io/origamitower/folktale?milestone=v2.0.0 and here https://github.com/origamitower/folktale/milestone/1

**Comment by robotlolita** [comment]
Closing this as it's already tracked by the v2.0.0 milestone.
