### ISSUE TITLE
Please review my 2 part blog post on FP

### ISSUE THREAD

**Issue by rajaraodv** [origamitower/folktale#55]
Hi there, 
I plan to post a series of blogs on FP w/ practical examples and How Tos. I would be great if you could give me some feedback.

To make orrections:
To make corrections, simply select the text and click on the "lock icon". It allows you to add private comments on the Medium itself.

Functional Programming In JS — With Practical Examples (Part 1)
https://medium.com/@rajaraodv/functional-programming-in-js-with-practical-examples-part-1-87c2b0dbc276

Functional Programming In JS — With Practical Examples (Part 2)
https://medium.com/@rajaraodv/functional-programming-in-js-with-practical-examples-part-2-429d2e8ccc9e

**Comment by robotlolita** [comment]
Sorry, I don't have the time for this now :(
