### ISSUE TITLE
What is "pattern" in catamorphism?

### ISSUE THREAD

**Issue by rajaraodv** [origamitower/folktale#56]
Could someone please give me an example of using catamorphism in Either Monad? Specifically I want to know aht "pattern" is in:
http://docs.folktalejs.org/en/latest/api/data/either/Either.html#data.either.Either.prototype.cata

**Comment by safareli** [comment]
```js
// readFileSync :: string -> Either Error string

readFileSync('./foo').cata({
  Left: err => console.error('fail :/', err),
  Right: str => console.log('boom', str),
})
```

**Comment by robotlolita** [comment]
The type:

```hs
@Either(α, β) => { r | Pattern } → γ
type Pattern {
  Left: α → γ,
  Right: β → γ
}
```

Reads as: "Given a `this` object, of type `Either(a, b)`, and an object containing at least the methods `Left: a -> c` and `Right: b -> c`, then it returns `c`".

So if you have something like:

```js
const a = Either.Left(1); // :: type Either(Number, X)
```

And you invoke the `.cata(pattern)` method, it expects an object that contains at least a `Left` and a `Right` method, and invokes the `Left` method with the contents of the Either:

```js
a.cata({
  Left: value => value + 1,
  Right: value => value - 1
});
// => 2
```

Likewise, if you have:

```
const b = Either.Right("foo"); // :: type Either(X, String)
```

And you invoke the `b.cata(pattern)` method, then pattern has to be an object with at least a `Left` and `Right` method, of which the `Right` method will be invoked with the contents of the Either:

```js
b.cata({
  Left: value => "Left: " + value,
  Right: value => "Right: " + value
});
// => "Right: foo"
```

It's pretty much a limited form of pattern matching that uses objects and methods to select the right operation to run, depending on the kind of value that you have. The newer Folktale deprecates the name `cata(pattern)` in favour of the much less cryptic `matchWith(pattern)` :)

Oh, as for the type notation, the `{ r | Pattern }` annotation uses a "row" type. In essence it means that any object needs to match exactly what's on the right of the `|`, but it may contain any other additional properties that the function does not use, and those properties are stored in the `r` (row) variable. It achieves the same thing as a subtype annotation (e.g.: `anyobject extends Pattern`).

**Comment by rajaraodv** [comment]
Thanks @robotlolita for the explanation. I think you should keep the name  **cata** because I have seen similar API in other libraries like: http://cwmyers.github.io/monet.js/#either and other places.

**Comment by robotlolita** [comment]
With the last patch, all structures now contain an example for `.matchWith`/`.cata`.
