### ISSUE TITLE
Remove meta/doc information from bundle

### ISSUE THREAD

**Issue by marvinhagemeister** [origamitower/folktale#61]
Thanks for an awesome library! While peeking through the code I was wondering weather all the meta information really belong into the final bundle.

There are lot's of strings inside the bundle, which are hard to compress. Removing them would likely make the bundle a lot smaller (wouldn't be surprised if the savings are approx **50%** or even more).

Things like this:
<img width="1139" alt="screen shot 2017-01-08 at 20 45 49" src="https://cloud.githubusercontent.com/assets/1062408/21753029/9a99f110-d5e3-11e6-9627-aa962ce8d534.png">

**Comment by robotlolita** [comment]
Oh hey.

We use the meta information to generate the docs, run documentation tests, and allow people to query documentation in the Node REPL. There'll be a browser bundle without it, but there's no easy command to generate one yet.

Right now, you can generate a bundle without the metadata by using this `.babelrc` configuration:

```json
{
  "presets": ["es2015", "es2016", "es2017"],
  "plugins": [
    "transform-function-bind",
    "transform-object-rest-spread",
    ["babel-plugin-module-alias", [
      { "src": "./src", "expose": "folktale" }
    ]]]
}
```

And then running:

```shell
$ make clean
$ FOLKTALE_DOCS=false make compile
$ make bundle
```

**Comment by marvinhagemeister** [comment]
Awesome, thanks a lot!
