### ISSUE TITLE
How to aggregate all success/failures in list of Validation (sequence?)

### ISSUE THREAD

**Issue by OliverJAsh** [origamitower/folktale#71]
Hi, thanks for the fantastic library and learning resources.

I have `Array<Validation<A, B>>` and want to aggregate all the successes and failures, e.g. `Array<Validation<A, B>> => Validation<Array<A>, Array<B>>`.

I thought this was possible using `control.monads.sequence`, however I seem to get runtime error `mr.chain` is not a function, so I presume I must be doing something wrong.

I have had success sequencing a list of `Either`s, but in my case I want to aggregate the left hand side as well, which from reading [this blog post](http://robotlolita.me/2013/12/08/a-monad-in-practicality-first-class-failures.html), it appears `Validation` should help.

Thanks!

**Comment by OliverJAsh** [comment]
Never mind, got it now!

``` js
// Array<Validation<A, B>> => Validation<Array<A>, Array<B>>
const sequenceValidations = validations => validations
    .map(validation => validation.map(success => [success]))
    .reduce((acc, validation) => (
        Validation.Success(a => b => a.concat(b)).ap(acc).ap(validation)
    ))
```

Is this function in the library anywhere?

**Comment by vendethiel** [comment]
Sounds a bit like http://stackoverflow.com/questions/39227232/futurelisterror-double-to-futurelisterror-listdouble-in-scala/39227649#39227649

**Comment by robotlolita** [comment]
@OliverJAsh Validations implement Applicative, rather than Monad, so `sequence` (which uses the Monad's interface `.chain`) doesn't work on them.

There isn't a function to aggregate Validations yet. Validations themselves already aggregate failures when you use .apply(), but the failure needs to have a `.concat` method. You can write a function to do this as:

```js
const Validation = require('folktale/data/validation');
const curry = require('folktale/core/lambda/curry');

const intoArray = (x) => Array.isArray(x) ? x : [x];

const collect = (validations) =>
  validations.map(x => x.failureMap(intoArray)).reduce(
    (a, b) => a.ap(b),
    Validation.of(curry(validations.length, (...values) => values))
  );
```

So something like:

```js
collect([a, b, c]);
```

Translates to:

```js
Validation.of((a, b, c) => [a, b, c])
  .ap(a.failureMap(intoArray))
    .ap(b.failureMap(intoArray))
      .ap(c.failureMap(intoArray))
```
