### ISSUE TITLE
.try in Either Type not documented

### ISSUE THREAD

**Issue by ferborva** [origamitower/folktale#73]
I've been going through the data.Either [documentation](http://docs.folktalejs.org/en/latest/api/data/either/Either.html) (might be old version and not supported as it's been migrated to origamitower) and haven't found any reference to the **.try** constructor. It's a shame as its very handy.

Also I've been in the [new documentation](http://origamitower.github.io/folktale/api/en/folktale.src.data.html) site and haven't seen the Either type in the 'data' Types. Is the migration in progress or will the type but dropped?

**Comment by robotlolita** [comment]
Ah, the old documentation was written manually, rather than generated from the code, so documentation and code'd get out of sync quite often (and it looks like I never got around adding `.try` to the docs Orz).

In the new library, Either has been renamed to Result: http://origamitower.github.io/folktale/api/en/folktale.src.data.result.try.try.html. Documentation for Result, Validation, Task, and Future is still WIP, but hopefully will be done by the end of this month.

**Comment by ferborva** [comment]
Oh ... Sorry for that then. Just out of curiosity then. Why call it 'Result'? Given it expresses a disjunction the name 'Either' seemed appropriate. Won't calling it 'Result' confuse it with 'Validation'?

**Comment by robotlolita** [comment]
There's a short justification here: https://github.com/origamitower/folktale/pull/62

`Result` is short for "the result of the operation" in a more imperative vocabulary. Not sure why Result'd be confused with Validation, but that's a valid concern.

**Comment by ferborva** [comment]
Thanks for the link to the renaming comment. My confusion came from Result's *Left* and *Right* being called *Error* and *Ok*, which seems like we would be validating or 'testing' something rather than offering two possible ways to go.

I don't know if I explained myself correctly ... either way (pun intended) thanks for the feedback :+1:

**Comment by robotlolita** [comment]
I'm adding some clarifications on when to use Result and when to use Validation in their documentation. Does this explanation seem reasonable to you, or is there something missing from it?  https://github.com/origamitower/folktale/blob/ea1cfd741ed54acd618cc92a7079fa41518717ab/docs/source/en/data/result/index.md#how-does-result-compare-to-validation

**Comment by ferborva** [comment]
Indeed this helps to see the different use cases for each Type. Thanks for the added info :top: 

Personally one of the things I like about Either/Result is its a bifunctor which allows me to part ways in a sequential computation, essentially offering two different roads depending on a previous decision/result. Given its still available all it will take is a little vocabulary adaption for future implementations with Result ;)
