### ISSUE TITLE
Chain/flatten for Validation type

### ISSUE THREAD

**Issue by OliverJAsh** [origamitower/folktale#75]
Hi, I am new to functional programming and have just started using Folktale after reading your fantastic blog posts.

I am wondering why Validation is not a Monad (and thus doesn't have `.chain`)? I have a use case where I have nested Validations and would really like to be able to chain them. As a very hacky workaround I'm having to convert to an Either and back:

``` js
// Validation<X, Validation<Y, Z> => Validation<X, Z> | Validation<Y, Z>
const flattenValidation = validation => (
    Validation.fromEither(
        Either.fromValidation(validation)
            .chain(validation2 => Either.fromValidation(validation2))
    )
)
```

Am I using Validations incorrectly?

**Comment by safareli** [comment]
I think converting back and forth is correct way to do that

**Comment by robotlolita** [comment]
This issue explains why Validations don't (and can't) have a `.chain` (i.e.: can't implement the Monad interface): https://github.com/folktale/data.validation/issues/15#issuecomment-223726909 (I should pull these all from the issues and put it in the FAQ as people frequently ask these things…)

Anyway, as for your problem, you can extract nested validations without the need to use chain, by using the `.matchWith` method directly:

```
//: Validation<X, Validation<Y, Z>> => Validation<X or Y, Z>
const flattenValidation = (validation) =>
  validation.matchWith({
    Failure: ({ value }) => Validation.Failure(value),
    Success: ({ value }) => value
  });
```

Ideally you wouldn't have nested validations though. Any particular reason you have them?

**Comment by OliverJAsh** [comment]
Fantastic, thanks for the great explanation @robotlolita.
