### ISSUE TITLE
Document Data.Task

### ISSUE THREAD

**Issue by OliverJAsh** [origamitower/folktale#77]
Hi there, I noticed the documentation for this new version of Folktale is currently missing `Task`.

Also, do you recommend using the old version of Folktale (the separate libraries i.e. `data.task`) until this new version is complete?

**Comment by robotlolita** [comment]
You can refer to https://github.com/origamitower/folktale/pull/50 while this doesn't land (just realised I didn't have an issue to track it). I'm going to write docs for Task once I'm done with the docs for Validation, so should be soon-ish.
