### ISSUE TITLE
"helpers" or "helpers-src"?

### ISSUE THREAD

**Issue by justin-calleja** [origamitower/folktale#91]
Skimming `tests` dir, I see a `helpers-src` dir. However, there are the following requires (which use "helpers" not "helpers-src"):

```
./test/helpers-src/fantasy-land-laws.js:11:const fl = require('folktale/helpers/fantasy-land');
./test/specs-src/data.maybe.js:12:const laws = require('../helpers/fantasy-land-laws');
./test/specs-src/data.result.js:12:const laws = require('../helpers/fantasy-land-laws');
./test/specs-src/data.validation.js:12:const laws = require('../helpers/fantasy-land-laws');
./test/specs-src/environment.js:13:const { Text } = require('../helpers/simple-structures');
```

Do you want the dir name as "helpers-src", and the requires to be changed or the other way round?

**Comment by robotlolita** [comment]
See [auto-generated files](https://github.com/origamitower/folktale/blob/patch/contributor-docs/CONTRIBUTING.md#how-is-folktale-organised) in the contributor documentation :)
