### ISSUE TITLE
Convert nodebacks to Task

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#96]
Folktale should support converting Node-back style functions to Tasks.

A Nodeback function is a function that accepts a callback in Node-style, for example:

```js
fs.readFile :: (pathname: String, callback: (Error or null, data: Buffer or String or null) => Void) => Void
```

A conversion function would take that `readFile` function and generate a new function that instead of taking a callback returns a Task object:

```js
nodebackToTask(fs.readFile) :: (pathname: String) => Task Error (Buffer or String)
```

## Where this goes?

In  the `data/conversions` module, as `nodebackToTask`.
In the `data/task` module, as `fromNodeback`.

Refer to existing `data/conversions` modules, and the `from*` functions in `data/maybe` and `data/either` to see more or less how this is done.

**Comment by rpearce** [comment]
@robotlolita I've just stumbled across this, but is [this](https://github.com/rpearce/task-from-fn/blob/master/index.js) the sort of thing you're looking for? I wrote a little lib the other day for converting functions with callbacks to Tasks to solve a simple problem and was considering expanding upon it. It's also short enough to include here:
```js
'use strict'

const Task = require('data.task')

function taskFromFn(fn, ctx) {
  return function() {
    var args = [].slice.call(arguments)

    return new Task(function(reject, resolve) {
      fn.apply(ctx,
        args.concat(function(err, data) {
          err ? reject(err) : resolve(data)
        })
      )
    })
  }
}

module.exports = taskFromFn
```
If so, I'd consider learning more about this library and taking a crack at a pull request!

**Comment by robotlolita** [comment]
@rpearce pretty much, yep :)

**Comment by rpearce** [comment]
Cool I'll take a stab next week at this!
